### ISSUE TITLE
"RuntimeError: this license key is expired" on docker container deployment

### ISSUE THREAD

**Issue by robineway** [dashingsoft/pyarmor#2130]
Corios has PyArmor Pro license key 007395. We are using PyArmor to apply an outer key to the Python launch script used to run our Python application from the linux CLI. The build mode of PyArmor works fine, and the runtime in conda works fine. 

When we build the runtime distribution of our application to a docker container and push to an Azure Container Registry, and then pull that docker image to an Azure linux VM, and then run this command: 
```
docker-compose run --rm translator /input/my_code_folder --config /config/my_custom_config.toml --html-report --log-file /output/custom_log.csv
```

we get this error: 
```
Traceback (most recent call last):
  File "/app/runsas2pyspark.py", line 3, in <module>
    from pyarmor_runtime_007395 import __pyarmor__
  File "/app/pyarmor_runtime_007395/__init__.py", line 2, in <module>
    from .pyarmor_runtime import __pyarmor__
RuntimeError: this license key is expired (1:11086)
```

The docker-compose.yml file is: 
```
services:
  translator:
    environment:
      - PYARMOR_RKEY=/app/translator_files/pyarmor.rkey
    image: coriostranslatorsecure.azurecr.io/corios-translator-secure-docker:2.8.4
    ports:
      - "22:22"  # Map SSH port
    volumes:
      - ./input:/input
      - ./output:/output
      - ./config:/config
      - ./license/pyarmor.rkey:/app/translator_files/pyarmor.rkey
 ```

we have used this script to generate new PyArmor outer keys, which we then copy into the docker distribution folder ./license: 
```
#!/usr/bin/env sh

# This script is used to generate a new PyArmor expiry key for the Corios Translator Secure.
# It uses PyArmor to generate a new expiry key, which then needs to be deployed to the target environment.
# This script is intended to be run on the build environment, not the deployment environment.
# The expiry key, called pyarmor.rkey, is sent to the deployment environment and replaces the old key.

# PYARMOR_EXPIRY_DATE is the updated date when the pyarmor license expires
PYARMOR_EXPIRY_DATE=2025-05-30

# change to the current user's home directory so that the updated pyarmor key doesn't collide with an old one
# This user needs to have the pyarmor license installed for this routine to work
cd ~
# apply pyarmor expiry date to the launch script
pyarmor gen key -e $PYARMOR_EXPIRY_DATE
```

We are not deploying our PyArmor build environment to the docker container and/or the target linux VM. We are only deploying the PyArmor runtime library like this: 
```
(azurecli) [rway@corios.org@ip-10-129-1-212 pyarmor_runtime_007395]$ ls -l
total 776
-rw-r--r--. 1 rway@corios.org domain_users@corios.org     99 Apr 22 00:04 __init__.py
-rwxr-xr-x. 1 rway@corios.org domain_users@corios.org 788264 Apr 22 00:04 pyarmor_runtime.so
```

How do we modify this configuration to resolve the "license key is expired" run time error?
