### ISSUE TITLE
pyproject.toml: pyarmor as build-backend

### ISSUE THREAD

**Issue by nschloe** [dashingsoft/pyarmor#641]
Modern Python projects define their build requirements in `pyproject.toml`, e.g.,
```toml
[build-system]
requires = [
  "setuptools>=42",
  "wheel",
]
build-backend = "setuptools.build_meta"
```
It'd be nice addition of pyarmor could be defined as the builder, e.g.,
```toml
[build-system]
requires = [
  "setuptools>=42",
  "wheel",
  "pyarmor>=7.2.0",
]
build-backend = "pyarmor.build_meta"
```
such that the resulting wheels are pyarmored.
